-- 1. BẢNG CHỨC VỤ (Mới - Để phân quyền)
CREATE TABLE CHUC_VU (
    CV_MA SERIAL PRIMARY KEY,
    CV_TEN VARCHAR(50) NOT NULL UNIQUE
);

-- 2. BẢNG NHÂN VIÊN (Nâng cấp từ QUAN_TRI_VIEN)
CREATE TABLE NHAN_VIEN (
    NV_MA SERIAL PRIMARY KEY,
    NV_TENDN VARCHAR(50) NOT NULL UNIQUE,
    NV_MATKHAU VARCHAR(255) NOT NULL,
    NV_TEN VARCHAR(100),
    NV_SDT VARCHAR(20),
    CV_MA INT REFERENCES CHUC_VU(CV_MA) ON DELETE SET NULL
);

-- 3. BẢNG ĐỐI TÁC (Chủ đầu tư, Nhà thầu...)
CREATE TABLE DOI_TAC (
    DT_MA SERIAL PRIMARY KEY,
    DT_TEN VARCHAR(150) NOT NULL,
    DT_LOAI VARCHAR(50), -- Nhà thầu, Chủ đầu tư, TVGS
    DT_EMAIL VARCHAR(150),
    DT_SDT VARCHAR(20),
    DT_DIACHI TEXT
);

-- 4. BẢNG DỰ ÁN (Mới - Theo yêu cầu quản lý thời gian thực)
CREATE TABLE DU_AN (
    DA_MA SERIAL PRIMARY KEY,
    DA_TEN VARCHAR(255) NOT NULL,
    DA_DIACHI TEXT,
    DA_NGAYTAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 5. BẢNG HỢP ĐỒNG (Nối Đối tác với Dự án)
CREATE TABLE HOP_DONG (
    HD_MA SERIAL PRIMARY KEY,
    HD_SOHIEU VARCHAR(50) UNIQUE NOT NULL,
    DT_MA INT REFERENCES DOI_TAC(DT_MA),
    DA_MA INT REFERENCES DU_AN(DA_MA),
    HD_NGAYKY DATE,
    HD_TRANGTHAI VARCHAR(50) DEFAULT 'active'
);

-- 6. BẢNG TIÊU CHUẨN & BIỂU MẪU (Nâng cấp từ SAN_PHAM)
-- Đáp ứng yêu cầu: Biểu mẫu cũ dùng công thức cũ
CREATE TABLE BIEU_MAU_CONG_THUC (
    BM_MA SERIAL PRIMARY KEY,
    BM_TEN VARCHAR(255) NOT NULL, -- Tên tiêu chuẩn: TCVN 7570:2006
    BM_CONG_THUC TEXT, -- Lưu công thức dạng JSON hoặc String
    BM_VERSION INT DEFAULT 1,
    BM_NGAY_CAP_NHAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    IS_ACTIVE BOOLEAN DEFAULT TRUE
);

-- 7. BẢNG PHÂN CÔNG CÔNG VIỆC (Nhiều - Nhiều như bạn yêu cầu)
CREATE TABLE PHAN_CONG (
    PC_MA SERIAL PRIMARY KEY,
    NV_MA INT REFERENCES NHAN_VIEN(NV_MA),
    HD_MA INT REFERENCES HOP_DONG(HD_MA),
    PC_NOI_DUNG TEXT,
    PC_NGAY_LAM DATE,
    PC_TRANG_THAI VARCHAR(50) DEFAULT 'processing'
);

-- 8. BẢNG QUYỀN HẠN (Nâng cấp từ ROLE)
CREATE TABLE roles (
    id INT AUTO_INCREMENT PRIMARY KEY,
    role_name VARCHAR(50) NOT NULL UNIQUE
);
CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    full_name VARCHAR(100),
    phone VARCHAR(20),
    role_id INT,
    FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE SET NULL
);